### ISSUE TITLE
Read only accounts

### ISSUE THREAD

**Issue by gcottletcc** [detunized/lastpass-ruby#14]
The `Vault.open_remote` method only returns accounts that I've created and is not returning my shared Read-Only accounts

**Comment by detunized** [comment]
This does library support shared folders. It's possible though that not all the special cases are handled correctly. At the moment I don't the time to investigate this. If you are willing to figure this out and submit a PR, you're more than welcome and it would be highly appreciated. Thanks.

**Comment by detunized** [comment]
@gcottletcc do you have any details on this. How do I reproduce this?

**Comment by detunized** [comment]
The issue is too old. No followup. Closing.
